cat 5.data | grep sp >> sp.out
cat 10.data | grep sp >> sp.out
cat 15.data | grep sp >> sp.out
cat 20.data | grep sp >> sp.out
cat 25.data | grep sp >> sp.out
cat 30.data | grep sp >> sp.out
cat 35.data | grep sp >> sp.out
cat 40.data | grep sp >> sp.out
cat 45.data | grep sp >> sp.out
cat 50.data | grep sp >> sp.out
cat 55.data | grep sp >> sp.out
cat 60.data | grep sp >> sp.out
cat 65.data | grep sp >> sp.out
cat 70.data | grep sp >> sp.out
cat 75.data | grep sp >> sp.out
cat 80.data | grep sp >> sp.out
cat 85.data | grep sp >> sp.out
cat 90.data | grep sp >> sp.out
cat 95.data | grep sp >> sp.out
cat 100.data | grep sp >> sp.out
cat 105.data | grep sp >> sp.out
cat 110.data | grep sp >> sp.out
cat 115.data | grep sp >> sp.out
cat 120.data | grep sp >> sp.out
cat 125.data | grep sp >> sp.out
cat 130.data | grep sp >> sp.out
cat 135.data | grep sp >> sp.out
cat 140.data | grep sp >> sp.out
cat 145.data | grep sp >> sp.out
cat 150.data | grep sp >> sp.out
cat 155.data | grep sp >> sp.out
cat 160.data | grep sp >> sp.out
cat 165.data | grep sp >> sp.out
cat 170.data | grep sp >> sp.out
cat 175.data | grep sp >> sp.out
cat 180.data | grep sp >> sp.out
cat 185.data | grep sp >> sp.out
cat 190.data | grep sp >> sp.out
cat 195.data | grep sp >> sp.out
cat 200.data | grep sp >> sp.out
